// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIIUoLNC5DLb-xyRAlHWYOZApIjkqAbw',
    appId: '1:661625693474:web:5d28780202cffdbedeb17b',
    messagingSenderId: '661625693474',
    projectId: 'portable-elderly-care-system',
    authDomain: 'portable-elderly-care-system.firebaseapp.com',
    storageBucket: 'portable-elderly-care-system.firebasestorage.app',
    measurementId: 'G-8Z4LY4KCCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJA5iB_aNmoD5gmpWKgR6b7OKZqfMRP4',
    appId: '1:661625693474:android:cca2ead303dcc7d6deb17b',
    messagingSenderId: '661625693474',
    projectId: 'portable-elderly-care-system',
    storageBucket: 'portable-elderly-care-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoRGyVwcV6Y0nBtc0J2UOXKrjl3d33XA',
    appId: '1:661625693474:ios:762940add91731f2deb17b',
    messagingSenderId: '661625693474',
    projectId: 'portable-elderly-care-system',
    storageBucket: 'portable-elderly-care-system.firebasestorage.app',
    iosBundleId: 'com.example.teamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEoRGyVwcV6Y0nBtc0J2UOXKrjl3d33XA',
    appId: '1:661625693474:ios:762940add91731f2deb17b',
    messagingSenderId: '661625693474',
    projectId: 'portable-elderly-care-system',
    storageBucket: 'portable-elderly-care-system.firebasestorage.app',
    iosBundleId: 'com.example.teamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARIIUoLNC5DLb-xyRAlHWYOZApIjkqAbw',
    appId: '1:661625693474:web:4a2eed18c15b8876deb17b',
    messagingSenderId: '661625693474',
    projectId: 'portable-elderly-care-system',
    authDomain: 'portable-elderly-care-system.firebaseapp.com',
    storageBucket: 'portable-elderly-care-system.firebasestorage.app',
    measurementId: 'G-3SWJQ7TVC6',
  );
}
